defaults:
  - semi_taks_t1_rlt_stage2_ac_mlp
  - _self_

runner:
  logger:
    experiment_name: semi_taks_t1_rlt_stage2_td3_mlp

algorithm:
  adv_type: rlt_td3
  loss_type: rlt_td3
  actor_agg_q: min
  actor_update_action_noise: true
  critic_actor_ratio: 2

actor:
  model:
    model_type: rlt_td3_mlp_policy
    mlp_hidden_dim: 256
    mlp_num_hidden_layers: 2
    actor_noise_sigma: 0.1
  optim:
    lr: 1.0e-4
  critic_optim:
    lr: 1.0e-4
  fsdp_config:
    wrap_policy:
      module_classes_to_wrap:
        - TwinQCritic
